import Link from "next/link";
import { ArrowRight, Check, CircleDollarSign, Clock3, HelpCircle, Menu, MessageCircle, ShieldCheck, Sparkles, Star, WalletCards } from "lucide-react";
import { auth } from "@/auth";

const features = [
  [MessageCircle, "Reddit work with a reward", "Find assignments for posts, comments, and conversations where the reward is visible before you begin."],
  [Check, "A brief you can act on", "TaskHorizon lays out the goal, the requirements, and the proof needed so you can work with confidence."],
  [WalletCards, "Know what your work is worth", "Each task has a stated reward. Approved submissions are added to your balance for payout."],
  [ShieldCheck, "Keep control of your account", "We never need your Reddit password or account access. You complete the work from your own account."],
  [Clock3, "One place for every task", "See open assignments, submissions awaiting review, and approved rewards without hunting through messages."],
  [HelpCircle, "Help is close by", "If a task is unclear, reach out through Discord or a support ticket before you submit."],
] as const;

const faqs = [
  ["What determines a task's reward?", "Rewards reflect the assignment's requirements. You will see the amount before deciding whether to claim the task."],
  ["What happens after I finish a task?", "Send the requested evidence through TaskHorizon. A reviewer checks it, then releases the reward for approved work."],
  ["Does it cost anything to use TaskHorizon?", "No. You can create an account, explore tasks, and start working without an upfront fee."],
  ["Will every task suit my Reddit account?", "Not necessarily. Requirements are listed on each assignment so you can choose opportunities that match your account."],
  ["Do I have to give TaskHorizon access to Reddit?", "No. You use your own Reddit account directly. TaskHorizon never asks for its password or login access."],
] as const;

export default async function RootPage() {
  const session = await auth();
  const workspace = session?.user ? (session.user.role === "ADMIN" ? "/admin" : "/dashboard") : "/register";
  const cta = session?.user ? "Open my workspace" : "Start earning now";

  return <main className="min-h-screen overflow-hidden bg-[linear-gradient(112deg,#102d44_0%,#0a3340_46%,#06272d_100%)] text-[#f5fffc]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6"><Link href="/" className="flex items-center gap-2.5 text-lg font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#c9ff5a] text-[#071b24]"><Sparkles className="h-4 w-4" /></span>TaskHorizon</Link><nav className="hidden items-center gap-8 text-sm text-[#b4c6c5] md:flex"><a href="#features" className="hover:text-white">Features</a><a href="#how" className="hover:text-white">How it works</a><a href="#faq" className="hover:text-white">FAQ</a></nav><div className="hidden items-center gap-3 sm:flex"><Link href="/login" className="text-sm font-semibold text-[#e8f2ef] hover:text-[#c9ff5a]">Log in</Link><Link href={workspace} className="rounded-full bg-[#c9ff5a] px-5 py-2.5 text-sm font-bold text-[#071b24] transition hover:bg-[#e0ff9b]">{session?.user ? "Workspace" : "Sign up"}</Link></div><Menu className="sm:hidden" /></header>

    <section className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-16 lg:grid-cols-[1.04fr_.96fr] lg:items-center lg:pb-28 lg:pt-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.06] px-3.5 py-2 text-xs font-semibold text-[#d7e6e3]"><span className="h-2 w-2 rounded-full bg-[#c9ff5a] shadow-[0_0_12px_#c9ff5a]" />Put your Reddit experience to work</div><h1 className="mt-7 max-w-3xl font-display text-5xl font-semibold leading-[0.97] tracking-[-0.055em] sm:text-7xl">Make your Reddit time<br /><span className="text-[#c9ff5a]">work for you.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#b4c6c5]">TaskHorizon connects you with paid Reddit assignments. Pick work that fits your account, follow a focused brief, and earn a reward when your submission is approved.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={workspace} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#c9ff5a] px-6 py-3.5 text-sm font-bold text-[#071b24] shadow-[0_12px_35px_rgba(201,255,90,0.2)] transition hover:-translate-y-0.5">{session?.user ? cta : "Find paid tasks"}<ArrowRight className="h-4 w-4" /></Link><a href="#how" className="inline-flex items-center justify-center rounded-full border border-white/15 px-6 py-3.5 text-sm font-bold text-white hover:bg-white/10">See the process</a></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-[#c4d3d1]"><Proof>No fee to join</Proof><Proof>Reward shown upfront</Proof><Proof>Your account stays private</Proof></div></div><ProductPreview /></section>

    <section className="border-y border-white/10 bg-[#062a31]/25 py-8"><div className="mx-auto grid max-w-5xl gap-6 px-5 text-center sm:grid-cols-3"><Stat value="Choose" label="a Reddit task" /><Stat value="Complete" label="the focused brief" /><Stat value="Earn" label="after approval" /></div></section>

    <section id="features" className="mx-auto max-w-7xl px-5 py-24"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#c9ff5a]">Built for practical Reddit work</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">A simple route from assignment to reward.</h2><p className="mt-5 leading-7 text-[#b4c6c5]">Everything is organized around the next useful action: choosing good work, completing it clearly, and knowing where your reward stands.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, text]) => <article key={title} className="rounded-2xl border border-white/10 bg-[#123b45]/80 p-6 shadow-[0_16px_42px_rgba(0,0,0,0.16)] backdrop-blur"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#071f27] text-[#c9ff5a]"><Icon className="h-5 w-5" /></span><h3 className="mt-10 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#b4c6c5]">{text}</p></article>)}</div></section>

    <section id="how" className="border-y border-white/10 bg-[#062a31]/25 px-5 py-24"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#c9ff5a]">How it works</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Three steps. One clear outcome.</h2><p className="mt-5 leading-7 text-[#b4c6c5]">Take on Reddit work when it suits you, with the details and reward visible from the start.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3"><Step number="01" title="Set up your profile" text="Tell us a little about yourself so you can access assignments that fit your account." /><Step number="02" title="Claim an assignment" text="Read the brief, accept a task you are comfortable with, and complete it on Reddit." /><Step number="03" title="Show your completed work" text="Upload the requested proof. After review, approved rewards are added to your balance." /></div></div></section>

    <section id="faq" className="mx-auto max-w-5xl px-5 py-24"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#c9ff5a]">Questions, answered</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">The essentials before your first assignment.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2">{faqs.map(([question, answer]) => <article key={question} className="rounded-2xl border border-white/10 bg-[#123b45]/80 p-6"><h3 className="font-bold">{question}</h3><p className="mt-3 text-sm leading-6 text-[#b4c6c5]">{answer}</p></article>)}</div></section>

    <section className="px-5 pb-24"><div className="mx-auto max-w-5xl rounded-[2rem] border border-white/10 bg-[#123b45]/80 px-7 py-14 text-center sm:px-16"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#c9ff5a]">Your next Reddit task is waiting</p><h2 className="mx-auto mt-4 max-w-2xl font-display text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Put a few focused minutes to better use.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-[#b9cecb]">Create your account, choose an assignment, and turn approved Reddit work into a reward.</p><Link href={workspace} className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#c9ff5a] px-6 py-3.5 text-sm font-bold text-[#071b24]">{session?.user ? "Open my workspace" : "Create an account"}<ArrowRight className="h-4 w-4" /></Link><p className="mt-5 text-xs text-[#b4c6c5]">No fee to join · Rewards shown before you start · Clear task requirements</p></div></section>
    <footer className="border-t border-white/10 px-5 py-7 text-center text-xs text-[#91aaa8]">© {new Date().getFullYear()} TaskHorizon. Reddit tasks with clear rewards.</footer>
  </main>;
}

function Proof({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center gap-1.5"><Check className="h-4 w-4 text-[#c9ff5a]" />{children}</span>; }
function Stat({ value, label }: { value: string; label: string }) { return <div><p className="font-display text-3xl font-semibold text-[#c9ff5a]">{value}</p><p className="mt-1 text-sm text-[#b4c6c5]">{label}</p></div>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <article className="rounded-2xl border border-white/10 bg-[#123b45]/80 p-7"><span className="font-mono text-sm font-bold text-[#c9ff5a]">{number}</span><h3 className="mt-9 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#b4c6c5]">{text}</p></article>; }
function ProductPreview() { return <div className="relative mx-auto w-full max-w-[510px]"><div className="absolute -right-8 top-10 h-48 w-48 rounded-full bg-[#c9ff5a]/20 blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-[#10323d] p-4 shadow-[0_30px_80px_rgba(0,0,0,.35)]"><div className="flex items-center justify-between rounded-2xl bg-white/[0.07] px-4 py-3 text-sm"><span className="font-semibold">Your task space</span><span className="rounded-full bg-[#c9ff5a] px-2.5 py-1 text-xs font-bold text-[#071b24]">Live</span></div><div className="mt-4 rounded-2xl bg-[#f6fffa] p-5 text-[#0c2228]"><div className="flex justify-between"><div><p className="text-xs font-semibold text-[#5c7675]">AVAILABLE REDDIT TASK</p><h3 className="mt-1 text-lg font-bold">Community response</h3></div><span className="rounded-lg bg-[#e8f7f1] px-3 py-2 text-sm font-bold text-[#11765f]">$2.00</span></div><p className="mt-5 text-sm leading-6 text-[#59716f]">Follow the task instructions, submit proof, and receive your reward after approval.</p><button className="mt-5 w-full rounded-xl bg-[#0c2730] py-3 text-sm font-bold text-white">Claim task</button></div><div className="mt-4 grid grid-cols-2 gap-4"><div className="rounded-2xl bg-white/[0.07] p-4"><p className="text-xs text-[#a8c2bf]">Active tasks</p><p className="mt-2 text-2xl font-bold">02</p></div><div className="rounded-2xl bg-white/[0.07] p-4"><p className="text-xs text-[#a8c2bf]">Approved</p><p className="mt-2 text-2xl font-bold">18</p></div></div></div></div>; }
